config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to:'static_page#index'
	get "/:page_name", to:'static_page#index'

	namespace :account do
		resources :users
		get "/:page_name", to:'users#dev'
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/account/users_controller.rb
class Account::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'account/index'
  # GET /users
  # GET /users.json
  def dev
    render template: "account/dev/#{params[:page_name]}"
  end

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to account_user_path(@user)
    else
      format.html { render :new }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.destroy
      redirect_to account_users_url
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
    
  end

  def show
    render template: "static_page/#{param[:page_name]}"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/account/index.html.haml
!!!
%html{:lang => "en"}
  %head
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %link{:href => "../assets/images/favicon.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
    %title Monster Admin Template - The Most Complete &amp; Trusted Bootstrap 4 Admin Template
    %link{:href => "/account/assets/plugins/bootstrap/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "/account/css/style.css", :rel => "stylesheet"}/

    %link#theme{:href => "/account/css/colors/blue.css", :rel => "stylesheet"}/
    %link#theme{:href => "/account/css/custom.css", :rel => "stylesheet"}/
  %body.fix-header.fix-sidebar.card-no-border

    .preloader
      %svg.circular{:viewbox => "25 25 50 50"}
        %circle.path{:cx => "50", :cy => "50", :fill => "none", :r => "20", "stroke-miterlimit" => "10", "stroke-width" => "2"}

    #main-wrapper
      =render('layouts/account/partials/header')
      =render('layouts/account/partials/left_menu')
      
          
      .page-wrapper
        .container-fluid
        
          =yield


    %script{:src => "/account/assets/plugins/jquery/jquery.min.js"}
    %script{:src => "/account/assets/plugins/bootstrap/js/tether.min.js"}
    %script{:src => "/account/assets/plugins/bootstrap/js/bootstrap.min.js"}
    %script{:src => "/account/js/jquery.slimscroll.js"}
    %script{:src => "/account/js/waves.js"}
    %script{:src => "/account/js/sidebarmenu.js"}
    %script{:src => "/account/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"}
    %script{:src => "/account/js/custom.min.js"}
    %script{:src => "/account/assets/plugins/flot/jquery.flot.js"}
    %script{:src => "/account/assets/plugins/flot.tooltip/js/jquery.flot.tooltip.min.js"}
    %script{:src => "/account/js/flot-data.js"}

    %script{:src => "/account/assets/plugins/styleswitcher/jQuery.style.switcher.js"}

app/views/layouts/account/partials/_header.html.haml
%header.topbar
  %nav.navbar.top-navbar.navbar-toggleable-sm.navbar-light
    .navbar-header
      %a.navbar-brand{:href => "index.html"}
        %b
          =image_tag('logo.png', class: 'img-responsive')
    .navbar-collapse

      %ul.navbar-nav.mr-auto.mt-md-0
        %li.nav-item
          %a.nav-link.nav-toggler.hidden-md-up.text-muted.waves-effect.waves-dark{:href => "javascript:void(0)"}
            %i.ti-menu
        %li.nav-item.hidden-sm-down
          %form.app-search.p-l-20
            %input.form-control{:placeholder => "Search for...", :type => "text"}/
            %a.srh-btn
              %i.ti-search

      %ul.navbar-nav.my-lg-0
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle.text-muted.waves-effect.waves-dark{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => ""}
            Cerrar Sesíon
            %i.fa.fa-sign-out

app/views/layouts/account/partials/_left_menu.html.haml
%aside.left-sidebar
  .scroll-sidebar
    %nav.sidebar-nav
      %ul#sidebarnav
        %li
          =link_to('<i class="fa fa-dashboard m-r-10"></i> Dashboard'.html_safe, account_users_path, class: 'waves-effect')
        %li
          =link_to('<i class="fa fa-plus-square-o m-r-10"></i> Realizar Deposito'.html_safe, 'deposito', class: 'waves-effect')
        %li
          =link_to('<i class="fa fa-archive m-r-10"></i> Depositos'.html_safe, 'depositos', class: 'waves-effect')
        %li
          =link_to('<i class="fa fa-paper-plane-o m-r-10"></i> Retirar Fondos'.html_safe, 'retirar', class: 'waves-effect')
        %li
          =link_to('<i class="fa fa-diamond m-r-10"></i> Ganancias'.html_safe, 'ganancias', class: 'waves-effect')
        %li
          =link_to('<i class="fa fa-users m-r-10"></i> Referidos'.html_safe, 'referidos', class: 'waves-effect')
        %li
          =link_to('<i class="fa fa-user m-r-10"></i> Mi Perfil'.html_safe, 'perfil', class: 'waves-effect')

app/views/layouts/application.haml
!!!
%html{:lang => 'es'}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Weblifepipo | plataform
    = csrf_meta_tags
    // Css de la pagina web estan el pagina public /frontend
    %link{:href => "frontend/css/bootstrap.css", :rel => "stylesheet"}/
    %link{:href => "frontend/plugins/owl/owl.carousel.css", :rel => "stylesheet"}/
    %link{:href => "frontend/plugins/owl/owl.theme.css", :rel => "stylesheet"}/
    %link{:href => "frontend/plugins/owl/owl.transitions.css", :rel => "stylesheet"}/
    %link{:href => "frontend/css/custom.css", :rel => "stylesheet"}/
    %link{:href => "frontend/css/responsive.css", :rel => "stylesheet"}/
    %link{:href =>"frontend/plugins/aos-master/aos.css", :rel => "stylesheet"}/
    %script{:src => "https://use.fontawesome.com/1303d34cbc.js"}
  %body

    = yield

    // Script del template
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js", :type=>"text/javascript"}
    %script{:src => "frontend/js/bootstrap.js", :type => "text/javascript"}
    %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAmiJjq5DIg_K9fv6RE72OY__p9jz0YTMI"}
    %script{:src => "frontend/plugins/map/map.js", :type => "text/javascript"}
    %script{:src => "frontend/plugins/niceScroll/niceScroll.min.js", :type => "text/javascript"}
    %script{:src => "frontend/plugins/videoBg/jquery.vide.js", :type => "text/javascript"}
    %script{:src => "frontend/plugins/owl/owl.carousel.js", :type => "text/javascript"}
    %script{:src => "frontend/plugins/aos-master/aos.js"}
    %script{:src => "frontend/js/common.js", :type => "text/javascript"}
    %script{:src => "frontend/plugins/numScroll/numscroller-1.0.js", :type => "text/javascript"}

app/views/partials/_about.haml
%section#about-section.grey-bg{:style => "padding-bottom: 60px;"}
  .container
    .row
      .col-md-12.col-sm-12.col-xs-12
        .services-div.margin-minus{"data-aos" => "fade-up", "data-aos-duration" => "1000"}
          .col-md-4.col-sm-4.col-xs-12.text-center.br.service-hover
            .service{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
              .service-icon
                %i.fa.fa-desktop
              .service-desc
                %h4.blue.oB Mineria
                %p.light.oR{:style => "text-align: center !important;"} Weblifepipo comenzó con unas pocas Redes Mineras hasta que expandimos nuestra red en Instalaciones complejas.
          .col-md-4.col-sm-4.col-xs-12.text-center.br.b0.service-hover
            .service{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
              .service-icon
                %i.fa.fa-area-chart
              .service-desc
                %h4.blue.oB Trading
                %p.light.oR{:style => "text-align: center !important;"} Nuestros expertos están plenamente cualificados para realizar un alto nivel de comercio y rendimiento para usted, 24 horas al día y 7 días a la semana, logrando un generoso margen de rentabilidad en un mega-mercado global.
          .col-md-4.col-sm-4.col-xs-12.text-center.br.b0.service-hover
            .service{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
              .service-icon
                %i.fa.fa-retweet
              .service-desc
                %h4.blue.oB Programa de Referidos
                %p.light.oR{:style => "text-aling: center !important;"} Nuestros usuarios, la clave más importante para este bussines recibirá un 5% de ganancias para cada nuevo miembro que ingresan.
          
    .row
      .col-md-12.col-sm-12.col-xs-12
        .col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1.col-xs-12.text-center
          #wwa
            .heading-text{"data-aos" => "fade-up", "data-aos-duration" => "1000"}
              %span.gold-gradient-color QUIENES SOMOS ?
            %p.light.oR{"data-aos" => "fade-up", "data-aos-duration" => "1000", :style => "text-aling: justify !important;"} Los miembros actuales de nuestro equipo minero bitcoin vienen de amigos que tratan de hacer un nuevo ingreso, la comprensión y la minería criptocurrencies nos ha reunido. Todos somos creyentes fuertes en el futuro de las monedas digitales y nos encanta ser parte de esta comunidad Weblifepipoing! Empezamos en un garaje construyendo mallas de minería simples, a medida que pasaba el tiempo empezamos a recibir computadoras viejas y ampliamos nuestra red. Pocos meses después las ganancias de la minería nos permitieron comprar equipos aún mejores hasta que nos expandimos en grandes almacenes.
            %button.btn.btn-gradient.outline-button.mtb20{"data-aos" => "zoom-in-up", "data-aos-duration" => "800", "data-target" => "#pop-about", "data-toggle" => "modal"}
              %div{:style => "background: #f1f1f1;transition: all 0.3s"}
                %span Leer mas de Nosotros

app/views/partials/_contact.haml
%footer#contact-section.sectionP60.dark-bg
  .container
    .row
      .col-md-12.col-sm-12.col-xs-12
        .col-md-7.col-sm-7.col-xs-12.pull-right.resCont
          .col-md-12.col-sm-12.col-xs-12
            .heading-text
              %span.gold-gradient-color Estar en contacto.
          %form{:action => ""}
            .col-md-12.col-sm-12.col-xs-12.p0
              .col-md-6.col-sm-6.col-xs-12
                .input-box
                  %input{:placeholder => "Nombre Completo", :required => "", :type => "text"}/
                  %span{:style => "position: absolute"}
                    %i.fa.fa-user
              .col-md-6.col-sm-6.col-xs-12
                .input-box
                  %input{:placeholder => "Email ", :required => "", :type => "text"}/
                  %span{:style => "position: absolute"}
                    %i.fa.fa-envelope-o
            .col-md-12.col-sm-12.col-xs-12.p0
              .col-md-6.col-sm-6.col-xs-12
                .input-box
                  %input{:placeholder => "Celular", :required => "", :type => "text"}/
                  %span{:style => "position: absolute"}
                    %i.fa.fa-phone
              .col-md-6.col-sm-6.col-xs-12
                .input-box
                  %input{:placeholder => "Asunto", :required => "", :type => "text"}/
                  %span{:style => "position: absolute"}
                    %i.fa.fa-puzzle-piece
            .col-md-12.col-sm-12.col-xs-12.p0
              .col-md-12.col-sm-12.col-xs-12
                .input-box
                  %textarea{:cols => "30", :id => "", :name => "", :placeholder => "Mensaje...", :rows => "5"}
                  %span{:style => "position: absolute"}
                    %i.fa.fa-comments
            %button.btn.btn-gradient.outline-button.pull-right.mtb20
              %div{:style => "background: #0C1222;transition: all 0.3s"}
                Enviar
                %tag.hidden-xs Mensaje
        .col-md-4.col-sm-5.col-xs-12.border-right.resCompany
          .company-desc.logoo
            %a{:href => "#home-section"}
              %img.img-responsive{:src => "frontend/images/logo3.png", :style => "height: 60px;"}/
            %p.light2.rl Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad atque corporis dignissimos eius eos est explicabo, impedit magnam magni.
          .meet-us
            %p.gold.rL Conocenos
            %span.light2.oR Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad atque corporis dignissimos eius eos est explicabo, impedit magnam magni.
          .cont-us
            %p.gold.rL Contáctemonos
            %div
              %a.light2.g{:href => "javascript:;"}
                %span.oR Linea fija : (+57) 1 234-5678
            %div
              %a.light2.g{:href => "javascript:;"}
                %span.oR Celular : +57 1234-5678
            %div
              %a.light2.g{:href => "javascript:;"}
                %span.oR Email : info@weblifepipo.com

app/views/partials/_header.haml
%section#home-section.header-bg
  .gradient.sectionP60.header-pad
    .container
      .row
        .col-md-12.col-sm-12.col-xs-12
          .row
            .col-md-5.col-sm-5.col-xs-12.header-text.sectionP60
              %h1.rL.white Web Life Pipo
              %h1.rL.white Deja que tu dinero, trabaje por ti!
              %p.rL.blue-L{:style => "text-align: justify !important;"} 
              %button.btn.btn-gradient{"data-aos" => "zoom-in-up", "data-aos-duration" => "800"} Adquirir Plan
            .col-md-6.col-sm-6.col-xs-12.pull-right
              .login-div.centered{"data-aos" => "fade-up", "data-aos-duration" => "1000"}
                .head
                  %h3.purple.oR.m0 Login | Web life pipo
                  %p.light.oR Introduzca sus credenciales
                  %form{:action => ""}
                    .body
                      .input-box
                        %input{:placeholder => "Email", :required => "", :type => "text"}/
                        %span{:style => "position: absolute"}
                          %i.fa.fa-user
                      .input-box
                        %input{:placeholder => "Contraseña", :required => "", :type => "password"}/
                        %span{:style => "position: absolute"}
                          %i.fa.fa-key
                  .foot
                    %a.forgot.pull-left{:href => "javascript:;"}
                      %small Olvidaste la Contraseña?
                    %button.btn.btn-gradient.W100.pull-right{"data-aos" => "zoom-in-up", "data-aos-duration" => "800"}Ingresar

app/views/partials/_modalRegister.haml
#pop-register.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-aos" => "zoom-in-up", "data-aos-duration" => "800", "data-dismiss" => "modal", :type => "button"} ×
        %h3.modal-title.blue.oR.m0 REGISTER
        %span.light.oR{:style => "font-size: 14px"} Enter your informations to register.
      %form{:action => ""}
        .modal-body
          .input-box
            %input{:placeholder => "Full Name", :required => "", :type => "text"}/
            %span{:style => "position: absolute"}
              %i.fa.fa-user
          .input-box
            %input{:placeholder => "Email Address", :required => "", :type => "email"}/
            %span{:style => "position: absolute"}
              %i.fa.fa-envelope-o
          .input-box
            %input{:placeholder => "Login Key", :required => "", :type => "text"}/
            %span{:style => "position: absolute"}
              %i.fa.fa-key
          .input-box
            %input{:placeholder => "Confirm Login Key", :required => "", :type => "text"}/
            %span{:style => "position: absolute"}
              %i.fa.fa-key
        .modal-footer
          %button.btn.btn-gradient{"data-dismiss" => "modal", :type => "button"} Register

app/views/partials/_modalabout.haml
#pop-about.modal.fade{:role => "dialog"}
  .modal-dialog.modal-lg
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-aos" => "zoom-in-up", "data-aos-duration" => "800", "data-dismiss" => "modal", :type => "button"} ×
        %h3.modal-title.gold-gradient-color.oR.m0 Nosotros
      .modal-body
        %p.light.oR
        %h3 Mineria
        Los miembros actuales de nuestro equipo minero bitcoin vienen de amigos que tratan de hacer un nuevo ingreso, la comprensión y la minería criptocurrencies nos ha reunido. Todos somos creyentes fuertes en el futuro de las monedas digitales y nos encanta ser parte de esta comunidad Weblifepipoing! Empezamos en un garaje construyendo mallas de minería simples, a medida que pasaba el tiempo empezamos a recibir computadoras viejas y ampliamos nuestra red. Pocos meses después las ganancias de la minería nos permitieron comprar equipos aún mejores hasta que nos expandimos en grandes almacenes.
        %p.light.oR
        %h3 Trading
        Queríamos expandirnos y ganar aún más dinero sin consumir tiempo ni energía, así que entramos en el comercio. Al principio fue muy complicado y perdimos pero cuando nos enteramos de criptones todo cambia. Las nuevas criptográficas nos permiten comerciar a un nuevo nivel y ganar poco tiempo. Weblifepipo hace el comercio de cryptones, cuenta con un equipo profesional, anal profesionales profesionales, que evalúan el mercado y hacer movimientos de acuerdo a las tendencias del mercado. Por ejemplo, si el bitcoin baja mucho durante la semana pasada, pero de acuerdo con el análisis de los comerciantes de esta semana se elevará hasta un cierto límite, lo harán va a comprar muchos bitcoins y luego venderlos a un precio más alto que Ya lo prevén, las transacciones pueden llegar a ganar cantidades increíbles de dinero.
        %p.light.oR
        %h3 Sistema de Referidos
        Nuestros usuarios, la clave más importante para este bussines recibirá un 5% de ganancias para cada nuevo miembro que ingresan.
      .modal-footer
        %button.btn.btn-gradient{"data-dismiss" => "modal", :type => "button"} Cerrar

app/views/partials/_navigation.haml
%nav.navbar.navbar-default
  .container
    .navbar-header.logoo
      %button#tog-btn.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#home-section"}
        %img.img-responsive{:src => "frontend/images/logo3.png", :style => "height: 50px;"}/
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right.hidden-xs.hidden-sm
        %li.gold
          %a{:href => "javascript:;"}
            %button.btn.btn-gradient.outline-button{"data-target" => "#pop-register", "data-toggle" => "modal", :style => "margin-bottom: 0px;"}
              %div{:style => "background: #1C589B;transition: all 0.3s;"} Registrate
      %ul#navigation.nav.navbar-nav.navbar-right
        %li
          %a.active{:href => "#home-section"} Inicio
        %li
          %a{:href => "#about-section"} Nosotros
        %li
          %a{:href => "#offers-section"} Ofertas
        %li
          %a{:href => "#contact-section"} Contactenos
      %ul.nav.navbar-nav.navbar-right.visible-xs.visible-sm
        %li.gold{:style => "border-top: 1px solid rgba(255,255,255,0.1)"}
          %a{"data-target" => "#pop-register", "data-toggle" => "modal", :href => "javascript:;"} Registrate

app/views/partials/_number.haml
%section.counter-bg
  .sectionP40.blue-bg
    .container
      .row
        .col-md-12
          .col-md-5.col-md-offset-0.col-sm-10.col-sm-offset-1.col-xs-12
            .responsive{"data-aos" => "fade-right", "data-aos-duration" => "1000"}
              .heading-text
                %span.gold-gradient-color Nuestro números
              %p.light2.oL{:style => "font-size: 16px;"} Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
              %button.btn.btn-gradient.outline-button.mtb20.hidden-sm.hidden-xs{"data-aos" => "zoom-in-up", "data-aos-duration" => "800"}
                %div{:style => "background: #091D48;transition: all 0.3s"} Registrate
          #counter.col-md-5.col-sm-12.col-xs-12.pull-right.resPad0
            .col-md-6.col-sm-3.col-xs-6.br.bb
              .numbers.text-center{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
                %span.numscroller.rB.gold-gradient-color{"data-delay" => "1", "data-increment" => "25", "data-max" => "4969", "data-min" => "0000"} 00
                %p.white.oR Downloads
            .col-md-6.col-sm-3.col-xs-6.bb
              .numbers.text-center{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
                %span.numscroller.rB.gold-gradient-color{"data-delay" => "1", "data-increment" => "25", "data-max" => "4670", "data-min" => "0000"} 00
                %p.white.oR Theme Lovers
            .col-md-6.col-sm-3.col-xs-6.br
              .numbers.text-center{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
                %span.numscroller.rB.gold-gradient-color{"data-delay" => "1", "data-increment" => "25", "data-max" => "4343", "data-min" => "0000"} 00
                %p.white.oR Followers
            .col-md-6.col-sm-3.col-xs-6
              .numbers.text-center{"data-aos" => "zoom-in", "data-aos-duration" => "1000"}
                %span.numscroller.rB.gold-gradient-color{"data-delay" => "1", "data-increment" => "25", "data-max" => "4546", "data-min" => "0000"} 00
                %p.white.oR Haters

app/views/partials/_pricingTable.haml
%section#pricing-table.sectionP60
  .container
    .row
      .col-md-12.col-sm-12.col-xs-12
        .col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1.col-xs-12.text-center
          %div
            .heading-text
              %span.gold-gradient-color Nuestros Planes
            %p.light.oR{:style => "font-size: 16px;"}
        .col-md-12.col-sm-12.col-xs-12.sectionP60
          .row
            .col-md-4.col-sm-4.col-xs-12
              .package
                .name Basico
                .price{:style => "font-size: 35px;"} 4%
                .trial Rentabilidad Diaria
                .lineDiv
                %ul
                  %li
                    %strong 0.1666% Hora
                  %li
                    %strong Min. Depósito 0,001 BTC
                  %li
                    %strong Máx. Depósito 5 BTC
                  %li
                    Pagos Automaticos
                %button.btn.btn-gradient.outline Adquirir plan
            .col-md-4.col-sm-4.col-xs-12
              .package.brilliant
                .name Standard
                .price{:style => "font-size: 35px;"} 6%
                .trial Rentabilidad Diaria
                .lineDiv
                %ul
                  %li
                    %strong 0.25% Hora
                  %li
                    %strong min. Depósito 5.001 BTC
                  %li
                    %strong max. Depósito 10 BTC
                  %li
                    Pagos Automaticos

                %button.btn.btn-white-outline Adquirir Plan
            .col-md-4.col-sm-4.col-xs-12
              .package
                .name Pro
                .price{:style => "font-size: 35px;"} %8
                .trial Rentabilidad Diaria
                .lineDiv
                %ul
                  %li
                    %strong 0.3333% Hora
                  %li
                    %strong min. Depósito 10.001 BTC
                  %li
                    %strong max. Depósito 500 BTC
                  %li
                    Pagos Automaticos

                %button.btn.btn-gradient.outline Adquirir Plan